export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'
export const FETCH_USER_RESET = 'FETCH_USER_RESET'

export const FETCH_SINGLE_USER_REQUEST = 'FETCH_SINGLE_USER_REQUEST'
export const FETCH_SINGLE_USER_SUCCESS = 'FETCH_SINGLE_USER_SUCCESS'
export const FETCH_SINGLE_USER_FAIL = 'FETCH_SINGLE_USER_FAIL'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const MESSAGE_CREATE_REQUEST = "MESSAGE_CREATE_REQUEST"
export const MESSAGE_CREATE_SUCCESS = "MESSAGE_CREATE_SUCCESS"
export const MESSAGE_CREATE_FAIL = "MESSAGE_CREATE_FAIL"

export const ROOM_CREATE_REQUEST = "ROOM_CREATE_REQUEST"
export const ROOM_CREATE_SUCCESS = "ROOM_CREATE_SUCCESS"
export const ROOM_CREATE_FAIL = "ROOM_CREATE_FAIL"

export const FETCH_MESSAGE_REQUEST = "FETCH_MESSAGE_REQUEST"
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS"
export const FETCH_MESSAGE_FAIL = "FETCH_MESSAGE_FAIL"

export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST"
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS"
export const DELETE_MESSAGE_FAIL = "DELETE_MESSAGE_FAIL"

export const FETCH_ROOMS_REQUEST = "FETCH_ROOMS_REQUEST"
export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS"
export const FETCH_ROOMS_FAIL = "FETCH_ROOMS_FAIL"

export const DELETE_ROOM_REQUEST = "DELETE_ROOM_REQUEST"
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS"
export const DELETE_ROOM_FAIL = "DELETE_ROOM_FAIL"

export const UPDATE_ROOM_REQUEST = 'UPDATE_ROOM_REQUEST'
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS'
export const UPDATE_ROOM_FAIL = 'UPDATE_ROOM_FAIL'

export const UPDATE_ONLINE_USER_REQUEST = 'UPDATE_ONLINE_USER_REQUEST'
export const UPDATE_ONLINE_USER_SUCCESS = 'UPDATE_ONLINE_USER_SUCCESS'
export const UPDATE_ONLINE_USER_FAIL = 'UPDATE_ONLINE_USER_FAIL'

export const UPDATE_OFFLINE_USER_REQUEST = 'UPDATE_OFFLINE_USER_REQUEST'
export const UPDATE_OFFLINE_USER_SUCCESS = 'UPDATE_OFFLINE_USER_SUCCESS'
export const UPDATE_OFFLINE_USER_FAIL = 'UPDATE_OFFLINE_USER_FAIL'